// MPC Music Memory

//mvp
// 2 players
// sequence
// win logic
// sounds
// css

// Features
// Best of Five
// sound FX (every 5/10 notes 5 second dnb track play (crank noisia) and flashing squares)
// booes when you loose
// css Fest
// Increased speed


//16pad grid needed with click events

//download image as background of mpc sampler.  Place buttons as links to samples stored in sample folder.
//player will be designed in css like DP work rather than styling divs.
//establish links to each button to a corresponding sound.
//add click event to each pad which will trigger a function that plays the correct sample.
//each pad will have have a unique color on click.
//create a gameplay box that will indicate the number of the round and whose turn it is to play


//variables - turncount, generated array, player1 array, player 2 array, player 1 lives, player 2 lives
//logic - on start

phase 1 - random sequence plays series of sounds 


// gameplay: play is pressed, message appears (Player 1 play), 5 seconds later i want the sounds to play from array with color flashes on the board.

//a play function that triggers the sequence 
//click event on play button will trigger this function
//the play function will be a loop.
//pause
//call a function that uses a random number generator and passes them to an array using push.  Array starts with 2.
//this function needs to be called twice until the array has 2 indexes so will have to be a loop.
//for loop - for( i = 0; i <= array.lengthl i ++), function play [i];
//each index's value in the array will be passed to a function that will play the corresponding sample.  0.5 second intervals to each sound.
//the audio play function will have to be called onece the loop has been broken.
//end of start

//methods needed - pushing, play, jquery, for each,
//each pad will have a jquery var which will trigger its sound.  
//

//then

// phase 2 - player clicks stores in an array

// gameplay:player then presses the same buttons. once the both have been pressed a 3 second rest, then the next sequence is played.  once the player loses all three lives, screen then says its player 2's go.

// //the player who has started needs to play the same pads that were generated by the random number generator. 
// //there then needs to be a pause when the player has time to press some buttons.  Using click event listeners each press of a buton will have to be pushed into an array which is then compared to sequence which was randomly generated.
// //if playerArray(1or2) == as generated array then then call play function again. else
// //player turn && player faults += 1.  

// //next round

// //start game needs to be called again except one number is then added to the sequence using a random number function. 
// //the .length of the array will have increased so the play function will loop over all of the indexes again.  The arrays will be stored as variables at the top. 

// //a function will then have to be called that performs inner html of who's go it is.

// get winner - palyer1's array .length will be compared to player two array.length and announce winner in scree.

// //The issue is that the the increment cant be called until the player has played the correct buttons.

// //Each player has three lives.  Once the first player has lost all their lives it is then player two's go.  The person who reached the highest level, wins.  

//there needs toe a reset button which brings the number of notes back to 2 and an alert to let player two know that it is his turn.































